# Generated by Django 3.1.2 on 2020-10-24 00:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inanutshell_app', '0003_files_docs'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='files',
            name='docs',
        ),
    ]
