# Generated by Django 3.1.2 on 2020-10-24 01:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inanutshell_app', '0006_auto_20201023_2119'),
    ]

    operations = [
        migrations.AlterField(
            model_name='files',
            name='docs',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
