# Generated by Django 3.0.5 on 2020-11-11 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inanutshell_app', '0007_auto_20201023_2154'),
    ]

    operations = [
        migrations.AddField(
            model_name='files',
            name='tag',
            field=models.CharField(default='SOME STRING', max_length=100),
        ),
    ]
