# Generated by Django 3.0.5 on 2020-11-14 21:26

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('inanutshell_app', '0008_files_tag'),
    ]

    operations = [
        migrations.AddField(
            model_name='files',
            name='summary',
            field=models.CharField(default='No Summary', max_length=3000),
        ),
        migrations.AddField(
            model_name='files',
            name='username',
            field=models.CharField(default='no user', max_length=100),
        ),
        migrations.AlterField(
            model_name='files',
            name='docs',
            field=models.FileField(default=django.utils.timezone.now, unique=True, upload_to=''),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='files',
            name='tag',
            field=models.CharField(default='OTHER', max_length=100),
        ),
    ]
